version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: 'mongodb'
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_USERNAME: paulina
      MONGO_INITDB_PASSWORD: paulina
